### ISSUE TITLE
How to change the  scheduling policy

### ISSUE THREAD

**Issue by hyc-yuchen** [hkust-adsl/kubernetes-scheduler-simulator#10]
我想复现您的论文，但是在我按照您的教程去实现的时候发现您并没有给出切换调度算法的方法，
而且在我执行第二步（Execute）的时候发现我的输出为如下图片，不知是否正确

I want to reproduce your paper, but when I follow your tutorial to implement it, I find that you did not give the method of switching scheduling algorithm.
Moreover, when I executed the second step (Execute), I found that my output was the following picture, I do not know whether it is correct

<img width="280" alt="捕获" src="https://github.com/hkust-adsl/kubernetes-scheduler-simulator/assets/61409162/e6cc693c-c68d-49a0-953e-187b6e12e6b5">

<img width="812" alt="捕获2" src="https://github.com/hkust-adsl/kubernetes-scheduler-simulator/assets/61409162/21b2985d-e6d0-4a7d-bff0-e1f3bbcab857">

**Comment by qzweng** [comment]
Hi @hyc-yuchen ,

Thanks for your interest in our project! Please find my response as follows,

1. Method of switching scheduling algorithm: The "01-Random", "02-DotProd", ..., "06-FGD" are actually different scheduling algorithms that we have implemented. To find more details about these policies, please refer to files under the "pkg/simulator/plugin" folder, such as "best_fit_score.go".

2. Execution failure: Based on your screenshot, it seems the configuration files were not successfully generated, which could be causing the execution failure. In my experience, a working directory should contain minimally a cluster config file (cc_xxx.yaml) and scheduler config file (sc_xxx.yaml), as shown in the example picture below (the analysis_xxx files are the outputs):

![image](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/assets/25865136/eac80513-ea69-4035-accd-445634786177)

**Comment by qzweng** [comment]
In case the issue stems from the environment, I would recommend you trying our prebuilt Docker image: https://hub.docker.com/r/qzweng/kubernetes-scheduler-simulator

```bash
# step 1: pull image
sudo docker pull qzweng/kubernetes-scheduler-simulator:atc23

# step 2: launch the docker container
sudo docker run -d --name=kss qzweng/kubernetes-scheduler-simulator:atc23 bash -c "sleep infinity"

# step 3: execute commands inside the container
sudo docker exec -it kss bash

# step 4: go to the project folder and conduct experiments
cd ~/kubernetes-scheduler-simulator
```

As these experiments have been successfully reproduced by the Artifact Evaluation Committee from USENIX ATC, I am confident that you can resolve the problem. Keep putting in smart efforts and trust yourself!

Feel free to let us know if you have any further questions or need additional assistance.

**Comment by hyc-yuchen** [comment]
> In case the issue stems from the environment, I would recommend you trying our prebuilt Docker image: https://hub.docker.com/r/qzweng/kubernetes-scheduler-simulator
> 
> ```shell
> # step 1: pull image
> sudo docker pull qzweng/kubernetes-scheduler-simulator:atc23
> 
> # step 2: launch the docker container
> sudo docker run -d --name=kss qzweng/kubernetes-scheduler-simulator:atc23 bash -c "sleep infinity"
> 
> # step 3: execute commands inside the container
> sudo docker exec -it kss bash
> 
> # step 4: go to the project folder and conduct experiments
> cd ~/kubernetes-scheduler-simulator
> ```
> 
> As these experiments have been successfully reproduced by the Artifact Evaluation Committee from USENIX ATC, I am confident that you can resolve the problem. Keep putting in smart efforts and trust yourself!
> 
> Feel free to let us know if you have any further questions or need additional assistance.

If I write my own algorithm, how do I add it, should I modify it in generate_config_and_run.py, and then run a similar simulation in run_scripts_0511.sh to get the corresponding data?

**Comment by qzweng** [comment]
Yes. To add a new policy: 
1. Implement it in Golang, see files under the "pkg/simulator/plugin" folder, such as "best_fit_score.go".
2. Build the code using `make`, see "Build from scratch" in repo's README
3. Make sure the `bin/simon` has been updated and ready for experiment.
4. Revise generate_config_and_run.py to add your policy into the experiment flow.
5. Run corresponding commands in run_scripts_0511.sh to trigger your experiment.

**Comment by hyc-yuchen** [comment]
> 4\. generate_config_and_run.py
Thank you for your reply. I will carry out the experiment. If I have any problems, I still need to ask you for help

**Comment by hyc-yuchen** [comment]
> Yes. To add a new policy:
> 
> 1. Implement it in Golang, see files under the "pkg/simulator/plugin" folder, such as "best_fit_score.go".
> 2. Build the code using `make`, see "Build from scratch" in repo's README
> 3. Make sure the `bin/simon` has been updated and ready for experiment.
> 4. Revise generate_config_and_run.py to add your policy into the experiment flow.
> 5. Run corresponding commands in run_scripts_0511.sh to trigger your experiment.

Thank you for your reply. I will carry out the experiment. If I have any problems, I still need to ask you for help
