### ISSUE TITLE
How to change the metric？

### ISSUE THREAD

**Issue by 1605wzf** [hkust-adsl/kubernetes-scheduler-simulator#12]
I'm highly interested in your project. I noticed that the evaluation metric referenced in your paper is the GPU allocation ratio within clusters. If I need to consider other metrics, such as SLO metrics during task scheduling, which part of the project code should I examine？

**Comment by qzweng** [comment]
Hi @1605wzf , 

Thanks for your interest! This Kubernetes scheduler is designed to replay cluster traces, which includes CPU/Mem/GPU requirements etc. (see [openb_pod_list_cpu050.csv](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/data/csv/openb_pod_list_cpu050.csv)), thus naturally considering allocation ratio as metrics.

If you want to add metrics like SLO satisfaction rate, I would suggest the following steps:
1. Find the data including these entries (out of the scope of this repo)
2. Revise the data processing script to handle new data (see [pod_csv_to_yaml.py](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/data/pod_csv_to_yaml.py))
3. See how these factors are considered in the scheduler's plugin and design your own ones. (see [best_fit_score.go](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/pkg/simulator/plugin/best_fit_score.go))
4. Update the cluster analysis function to report your desired metrics (see [analysis.go](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/pkg/simulator/analysis.go)).

Hope this helps!

**Comment by 1605wzf** [comment]
> Hi @1605wzf , 你好
> 
> Thanks for your interest! This Kubernetes scheduler is designed to replay cluster traces, which includes CPU/Mem/GPU requirements etc. (see [openb_pod_list_cpu050.csv](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/data/csv/openb_pod_list_cpu050.csv)), thus naturally considering allocation ratio as metrics.感谢您的关注！此 Kubernetes 调度器旨在重放集群跟踪，其中包括 CPU/Mem/GPU 要求等（见openb_pod_list_cpu050.csv），因此自然而然地将分配比率视为指标。
> 
> If you want to add metrics like SLO satisfaction rate, I would suggest the following steps:如果您想添加 SLO 满意度等指标，我建议执行以下步骤：
> 
> 1. Find the data including these entries (out of the scope of this repo)查找包含这些条目的数据（超出此存储库的范围）
> 2. Revise the data processing script to handle new data (see [pod_csv_to_yaml.py](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/data/pod_csv_to_yaml.py))修改数据处理脚本以处理新数据（请参阅pod_csv_to_yaml.py）
> 3. See how these factors are considered in the scheduler's plugin and design your own ones. (see [best_fit_score.go](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/pkg/simulator/plugin/best_fit_score.go))了解调度程序插件中如何考虑这些因素，并设计您自己的因素。（见 best_fit_score.go）
> 4. Update the cluster analysis function to report your desired metrics (see [analysis.go](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/pkg/simulator/analysis.go)).更新聚类分析函数以报告所需的指标（请参阅 analysis.go）。
> 
> Hope this helps! 希望这会有所帮助！

Thank you for your reply. I will carry out the experiment.

> Hi @1605wzf ,
> 
> Thanks for your interest! This Kubernetes scheduler is designed to replay cluster traces, which includes CPU/Mem/GPU requirements etc. (see [openb_pod_list_cpu050.csv](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/data/csv/openb_pod_list_cpu050.csv)), thus naturally considering allocation ratio as metrics.
> 
> If you want to add metrics like SLO satisfaction rate, I would suggest the following steps:
> 
> 1. Find the data including these entries (out of the scope of this repo)
> 2. Revise the data processing script to handle new data (see [pod_csv_to_yaml.py](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/data/pod_csv_to_yaml.py))
> 3. See how these factors are considered in the scheduler's plugin and design your own ones. (see [best_fit_score.go](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/pkg/simulator/plugin/best_fit_score.go))
> 4. Update the cluster analysis function to report your desired metrics (see [analysis.go](https://github.com/hkust-adsl/kubernetes-scheduler-simulator/blob/main/pkg/simulator/analysis.go)).
> 
> Hope this helps!

Thank you for your reply. I will carry out the experiment.
