### ISSUE TITLE
go mod vendor出现了问题

### ISSUE THREAD

**Issue by lckkkk02** [hkust-adsl/kubernetes-scheduler-simulator#14]
>go mod vendor
go: github.com/alibaba/open-local@v0.2.4-0.20211118031547-952eadbb4a8e requires
        github.com/peter-wangxu/simple-golang-tools@v0.0.0-20210209091758-458c22961dd2: invalid version: unknown revision 458c22961dd2

**Comment by mental2008** [comment]
Could you please provide some details about your local environment (e.g., OS and Go version)? As a reference, we have successfully executed the commands on both Linux and macOS. If you are still facing this issue, we suggest utilizing the Docker environment that we have made available in the README file. This environment comes pre-configured with Golang, Python, and all the necessary libraries, which should allow you to run the code without any further configurations.
