### ISSUE TITLE
support gang-scheduling

### ISSUE THREAD

**Issue by BhAem** [hkust-adsl/kubernetes-scheduler-simulator#16]
Does this simulator support gang-scheduling for multi-machine and multi-GPU training?

**Comment by qzweng** [comment]
Thank you for your question on gang-scheduling.

The simulator **does support** scheduling pods that require multiple GPUs. Additionally, you can deploy a job-level operator on the Kubernetes cluster to enhance gang-scheduling for multi-machine training jobs, while still utilizing pod-level scheduling policies like FGD within the simulator.

Please feel free to reach out if you have any further questions!
