### ISSUE TITLE
When exec run_scripts_0511.sh, xargs: argument line too long

### ISSUE THREAD

**Issue by wenzhaojie** [hkust-adsl/kubernetes-scheduler-simulator#9]
I have tried this:
```bash
cat experiments/run_scripts/run_scripts_0511.sh | while read i; do printf "%q" "$i"; done | xargs --max-procs=16 -I CMD bash -c CMD
```
But it appears to be "xargs: argument line too long". How could this happen? Thx!

**Comment by qzweng** [comment]
Sorry for the belated reply! As a quick work around, it is suggested to manually run the commands in run_scripts_0511.sh line by line, instead of calling xargs. In essence, the xargs is to parallel the execution of these commands with a maximum parallelism level of 16 threads.
